### PR TITLE
⬆️(front) upgrade draft-js plugins lib

### PR DESCRIPTION
**Pull request by carofun**
## Purpose

Plugins used in draft-js have changed their namespace. We want to update our code with their latest version.

## Proposal

Update the project

- Update package.json with their latest version
- Change their import
- Test draft-js

Capture d’écran 2021-01-20 à 11 44 59

### CODE REVIEW

**Review by madmatah — COMMENTED** [review]
Great! :tada: 

Since the static toolbar plugin is now in typescript, I think you can remove the types that we declared in the project for the old JS version of this plugin.

**Comment by carofun** [comment]
> Great! 🎉
> 
> Since the static toolbar plugin is now in typescript, I think you can remove the types that we declared in the project for the old JS version of this plugin.

And it still works indeed !

**Comment by madmatah** [comment]
I have a suggestion regarding the commit message body, to keep track of what we updated, and why : 

```
Some draft-js related dependencies have changed their namespace and were not updated automatically by dependabot.
So we had to rename and update them.

- draft-js-anchor-plugin (2.0.3) has been replaced with @draft-js-plugins/anchor (4.0.0)
- draft-js-buttons (2.0.2) has been replaced with @draft-js-plugins/buttons (4.0.0)
- draft-js-plugins-editor (3.0.0) has been replaced with @draft-js-plugins/editor (4.0.0)
- draft-js-static-toolbar-plugin (3.0.1) has been replaced with @draft-js-plugins/static-toolbar (4.0.0)
```

**Review by madmatah — APPROVED** [review]

**Pull request merged**
