### PR TITLE
🎨(front) reorganize CSS files

### PR DESCRIPTION
**Pull request by madmatah**
## Purpose

Ashley is using CSS files distributed with django-machina.
It does not allow to reuse SASS variables.

## Proposal

- [x] Build the CSS inside Ashley project
- [x] Import django-machina SASS files
- [x] Use the latest bootstrap version
- [x] Use the latest font-awesome version

### CODE REVIEW

**Comment by lunika** [comment]
You made a complete copy of django-machina sass files into the front project ?

**Comment by madmatah** [comment]
> You made a complete copy of django-machina sass files into the front project ?

Yes in the [`objects` folder](https://github.com/openfun/ashley/tree/feature/style/src/frontend/scss/objects) , to have a base theme. And then, we'll be able to customize it more easily.

**Comment by lunika** [comment]
> > You made a complete copy of django-machina sass files into the front project ?
> 
> Yes in the [`objects` folder](https://github.com/openfun/ashley/tree/feature/style/src/frontend/scss/objects) , to have a base theme. And then, we'll be able to customize it more easily.

Did you plan something to follow django-machina evolution ?

**Comment by madmatah** [comment]
> > > You made a complete copy of django-machina sass files into the front project ?
> > 
> > 
> > Yes in the [`objects` folder](https://github.com/openfun/ashley/tree/feature/style/src/frontend/scss/objects) , to have a base theme. And then, we'll be able to customize it more easily.
> 
> Did you plan something to follow django-machina evolution ?

This is mostly built on bootstrap with some little adjustments in machina SCSS files.
The goal is to have our own theme soon.

In the meanwhile, we'll have to be take a look at django-machina evolutions when new versions are released, yes. But the same applies to the django part, since we have overridden some django-machina apps, to customize some models and templates.

**Comment by jmaupetit** [comment]
I'm sure @madmatah can generate a patch with git for scss files from django-machina (between two releases).

**Pull request merged**
